apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-proxyserver
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    helm.sh/chart: {{ include "hadoop.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: yarn-proxyserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: yarn-proxyserver
  minAvailable: {{ .Values.yarn.proxyServer.pdbMinAvailable }}
